### ISSUE TITLE
defclass from tutorial example does not work for python3.8

### ISSUE THREAD

**Issue by dineshbhardwaj** [hylang/hy#1919]
This code given in the document does not work with hy3 ( python3.8 installed ) -- 
```(defclass FooBar []
  (defn __init__ [self x]
    (setv self.x x))
  (defn get-x [self]
    self.x))
```

here is the error i am getting -- 
```
=> (defclass FooBar []
  (defn __init__ [self x]
    (setv self.x x))
  (defn get-x [self]
    self.x))
Traceback (most recent call last):
  File "/Users/Apple/Library/Python/3.8/bin/hy3", line 8, in <module>
    sys.exit(hy_main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code.py", line 232, in interact
    more = self.push(line)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code.py", line 258, in push
    more = self.runsource(source, self.filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codeop.py", line 171, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
ImportError: cannot import name 'lexer' from partially initialized module 'hy.lex.lexer' (most likely due to a circular import) (/Users/Apple/Library/Python/3.8/lib/python/site-packages/hy/lex/lexer.py)
```
Let e know if i missed anything, as lot of other things are working correctly on hy3.

**Comment by Kodiologist** [comment]
I can't reproduce this. Are you running Hy master?

**Comment by dineshbhardwaj** [comment]
bash-3.2$ hy3 
hy 0.19.0 using CPython(default) 3.8.3 on Darwin
=>

**Comment by Kodiologist** [comment]
So then install Hy master and try it again.

**Comment by dineshbhardwaj** [comment]
I tried with the latest version from master downloaded 2 minutes back. I am still getting the same issue. I am ok for a remote session too to debug the issue.

**Comment by dineshbhardwaj** [comment]
Looks like something screwed up while reinstalling.  It got resolved after : 
```
pip3.8 uninstall hy
rm -rf /Users/<user name>/Library/Python/3.8/lib/python/site-packages/hy/
```
and then reinstalling.

**Comment by Kodiologist** [comment]
Perhaps your `json.hy` was being read instead of the standard Python module `json`. It's never wise to give a Python or Hy file the same name as a standard module.
