### PR TITLE
Fix issue found by @tuturto in #903

### PR DESCRIPTION
**Pull request by kirbyfan64**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
@tuturto @gilch Please try this!

**Comment by kirbyfan64** [comment]
(FYI, this doesn't work with Python 2 yet, hold on a sec...)

**Comment by kirbyfan64** [comment]
Ok, now it works with Python 2.

**Comment by gilch** [comment]
An issue from #924, uncovered by testing #903, rather, for the record.

**Comment by tuturto** [comment]
With this ```defmacro!``` is working. Great!

However, something else was broken in ```defmacro``` as this doesn't work anymore:
```
(defn test-defclass-macroexpand []
  "NATIVE: test defclass with macro expand"
  (defmacro M [] `(defn x [self x] (setv self._x x)))
  (defclass A [] (M))
  (setv a (A))
  (a.x 1)
  (assert (= a._x 1)))
```
I get a traceback:
```
hy.errors.HyCompileError: Internal Compiler Bug �
⤷ IndexError: string index out of range
Compilation traceback:
File "/home/tuukka/programming/hy/hy/compiler.py", line 432, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/tuukka/programming/hy/hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/tuukka/programming/hy/hy/compiler.py", line 1949, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/tuukka/programming/hy/hy/compiler.py", line 424, in compile_atom
    ret = _compile_table[atom_type](self, atom)
  File "/home/tuukka/programming/hy/hy/compiler.py", line 366, in checker
    return fn(self, expression)
  File "/home/tuukka/programming/hy/hy/compiler.py", line 2332, in compile_class_expression
    expr = rewire_init(macroexpand(expression, self.module_name))
  File "/home/tuukka/programming/hy/hy/macros.py", line 155, in macroexpand
    tree = macroexpand_1(tree, module_name)
  File "/home/tuukka/programming/hy/hy/macros.py", line 178, in macroexpand_1
    m_copy = make_empty_fn_copy(m)
  File "/home/tuukka/programming/hy/hy/macros.py", line 135, in make_empty_fn_copy
    if a[0] == '*':
```

**Comment by gilch** [comment]
I think we've lost our purpose here.
```
=> (let)
  File "<input>", line 1, column 1

  (let)
  ^---^
HyMacroExpansionError: expanding `let': missing 1 required positional argument:
'_0'
```
What's a '_0'? The whole point of #924 was to *improve* the error messages. At least the `TypeError` we had before said the missing argument is named "variables". This is worse. As it stands, we'd be better off reverting #924 altogether than accepting this fix for it.

Why exactly was it failing for Python2? Can we make it work in Python2 by building the lambda from AST instead of a string? Do we know why exactly the `getargspec` was failing for only certain macros? Can we fix the macro system so it returns supported callables instead of giving up on unsupported callables? (whatever that means?)

**Comment by tuturto** [comment]
I really would like to see #924 working with #903 and this, since better error messages is always a good idea. If I have time, I'll try poking around the code in the evening.

**Comment by kirbyfan64** [comment]
@gilch @tuturto Fixed. Git screwed my commit history so it doesn't appear correctly on GitHub...but, other than that, the actual code works.

**Comment by kirbyfan64** [comment]
Hmm...this is a GitHub issue. It's showing up correctly in my Git history...
